db.companyDrives.insertMany([
    {
        id:1,
        name:"Amazon",
        date:ISODate("2020-10-16"),
        studentAppeared:["Bala","Vetri","Vinoth"]
    },
    {
        id:2,
        name:"Zoho",
        date:ISODate("2020-10-19"),
        studentAppeared:["Bala","Nirmal","Vinoth","Kailash"]
    },
    {
        id:3,
        name:"Apple",
        date:ISODate("2020-10-20"),
        studentAppeared:["Nirmal","Kailash","Vinoth"]
    },
    {
        id:4,
        name:"Google",
        date:ISODate("2020-10-17"),
        studentAppeared:["Bala","Vetri","Nirmal","Kailash"]
    }
])