db.topic.insertMany([
    {
        id:1,
        name:"javascript",
        month:"October",
        date:ISODate("2020-10-15")
    },
    {
        id:2,
        name:"HTML",
        month:"October",
        date:ISODate("2020-10-16")
    },
    {
        id:3,
        name:"CSS",
        month:"October",
        date:ISODate("2020-10-17")
    },

    {
        id:4,
        name:"DOM",
        month:"October",
        date:ISODate("2020-10-18")
    },
    {
        id:5,
        name:"Promise",
        month:"October",
        date:ISODate("2020-10-19")
    },
    {
        id:6,
        name:"Hooks",
        month:"October",
        date:ISODate("2020-10-20")
    },
    {
        id:7,
        name:"CRUD using hooks",
        month:"October",
        date:ISODate("2020-10-22")
    },
    {
        id:8,
        name:"Reducer",
        month:"November",
        date:ISODate("2020-11-05")
    },
    {
        id:9,
        name:"ContextAPI",
        month:"November",
        date:ISODate("2020-11-06")
    },
    {
        id:10,
        name:"SQL",
        month:"November",
        date:ISODate("2020-11-07")
    }
])